version: "3.9"

services:
  keycloak:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    ports:
      - '9100:9100'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KC_HTTP_PORT: 9100
      KC_METRICS_ENABLED: 'true'
      KC_LOG_CONSOLE_COLOR: 'true'
      KC_HEALTH_ENABLED: 'true'
      #KC_LOG_LEVEL: DEBUG
    command:
      - start-dev

  postgres:
    image: postgres
    environment:
      - "POSTGRES_USER=keycloak"
      - "POSTGRES_DB=keycloak"
      - "POSTGRES_PASSWORD=keycloak"
        